name: CI
on:  
  pull_request:    
    branches:
    - master  
  push:
    branches:
    - master
jobs:  
  build:     
   runs-on: ubuntu-latest
   
   steps:    
   - uses: actions/checkout@v1
   - name: Build and test with Docker
     run: |
       docker build --tag python .
       docker run --rm python pytest python
       
jobs:
  build:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./github-action-pytest
