name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6.0
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.0
    - name: Test with pytest
      run: |
        pip3 install pytest
        pytest
